
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - usersdb2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - usersdb2s/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - usersdb2s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.example.com
  resources:
  - usersdbbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - usersdbbackups/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - usersdbbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cache.example.com
  resources:
  - usersdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - usersdbs/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - usersdbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
