# permissions for end users to view usersdb2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usersdb2-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - usersdb2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - usersdb2s/status
  verbs:
  - get
