# permissions for end users to edit usersdb2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usersdb2-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - usersdb2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - usersdb2s/status
  verbs:
  - get
